In [1]:
import os
import numpy as np
import sys
#import pandas as pd
#import xml.etree.ElementTree as ET
import csv
import json
#import numpy
import scipy
#from xml.dom import minidom
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#Reading data  (CSV file)
#file_name1= '/home/Desktop/spreaductaion/Data/tutor_profile.csv'
file_name1= '~/Desktop/spreaducation/Data/tutor_profile.csv'

file_name2= '~/Desktop/spreaducation/Data/tutee_profile.csv'

#machine=pd.read_json(file_name1)

#file_name2= '/home/Desktop/spreaducation/Data/tutee_profile.csv'

In [3]:
#Reading data  (CSV file)
#file_name1= '/home/Desktop/spreaductaion/Data/tutor_profile.csv'
file_name3= '~/Desktop/spreaducation/Data/QueryresultsDISC.csv'

file_name4= '~/Desktop/spreaducation/Data/QueryresultsPSYCHO.csv'

#machine=pd.read_json(file_name

#file_name2= '/home/Desktop/spreaducation/Data/tutee_profile.csv'

In [4]:
tutors = pd.read_csv(file_name1)

tutees = pd.read_csv(file_name2)

In [5]:
disc = pd.read_csv(file_name3)

psycho = pd.read_csv(file_name4)

In [6]:
tutors.head(0)

Empty DataFrame
Columns: [user_id, gender, dob, main_language, description, institute_attended, occupation, occupation_degree, working_language, subject_1, subject_1_level, subject_2, subject_2_level, subject_3, subject_3_level, subject_4, subject_4_level, interest_1, time_interest_1, interest_2, time_interest_2, interest_3, time_interest_3, wished_salary, lesson_type, place]
Index: []

[0 rows x 26 columns]

In [28]:
tutees.head(5)

,user_id,gender,dob,class_level,school_name,main_language,subject_improve_1,score_subject_improve_1,subject_goodat_1,score_subject_goodat_1,...,interest_2,time_interest_2,interest_3,time_interest_3,subject_improve_2,score_subject_improve_2,subject_goodat_2,score_subject_goodat_2,tutor_order,tutor_id
0,1e9e2a24-006b-48fd-a649-6d5f3f33ecd4,Female,2006-01-20,7,Dreilinden Grundschule,German,Math,2,German,1,...,Foosball,4,MeetFriends,5,History,2,English,1,NaN,NaN
1,6c28e282-6f8e-4184-96e4-81eaff0aa0b0,Male,2004-03-31,8,Werner von Siemens Gymnasium,German,Math,4,English,2,...,Tennis,3,VideoGames,5,German,4,Chemistry,2,NaN,NaN
2,046059ed-ed1e-4982-ad7a-f1f55f6b1698,Male,2003-11-19,9,Schadow-Gymnasium,German,German,4,Other,1,...,TableTennis,4,Other,3,Spanish,4,Geography,2,2.0,581e3d54-6a2e-4a1f-bdd5-6890fee295f1
3,264cd3e8-2ded-41e9-9b73-0708beb18c3e,Female,2003-05-06,9,Schadow gymnasium,German,Chemistry,5,English,2,...,Art,2,Fashion,5,Math,5,Other,1,8.0,56bc0301-e5e4-4552-81cd-90ef9a3f26c8
4,02e6e91c-a570-4eb9-849e-3ddfeb59ce06,Male,2003-05-04,9,Schadow Gymnasium,German,Physics,3,History,1,...,Foosball,4,MeetFriends,5,Chemistry,3,Geography,2,2.0,6c12340c-1dee-486e-b9be-e6f94dbae12e

In [31]:
tutors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 26 columns):
user_id               17 non-null object
gender                17 non-null object
dob                   17 non-null object
main_language         17 non-null object
description           17 non-null object
institute_attended    17 non-null object
occupation            17 non-null object
occupation_degree     17 non-null object
working_language      17 non-null object
subject_1             17 non-null object
subject_1_level       17 non-null int64
subject_2             17 non-null object
subject_2_level       17 non-null int64
subject_3             12 non-null object
subject_3_level       12 non-null float64
subject_4             10 non-null object
subject_4_level       10 non-null float64
interest_1            17 non-null object
time_interest_1       17 non-null int64
interest_2            17 non-null object
time_interest_2       17 non-null int64
interest_3            17 non-null object
time_interest_3       17 non-null int64
wished_salary         17 non-null int64
lesson_type           17 non-null object
place                 17 non-null object
dtypes: float64(2), int64(6), object(18)
memory usage: 3.5+ KB

In [34]:
tutees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 22 columns):
user_id                    71 non-null object
gender                     71 non-null object
dob                        71 non-null object
class_level                71 non-null int64
school_name                71 non-null object
main_language              71 non-null object
subject_improve_1          71 non-null object
score_subject_improve_1    71 non-null int64
subject_goodat_1           71 non-null object
score_subject_goodat_1     71 non-null int64
interest_1                 71 non-null object
time_interest_1            71 non-null int64
interest_2                 71 non-null object
time_interest_2            71 non-null int64
interest_3                 71 non-null object
time_interest_3            71 non-null int64
subject_improve_2          71 non-null object
score_subject_improve_2    71 non-null int64
subject_goodat_2           71 non-null object
score_subject_goodat_2     71 non-null int64
tutor_order                63 non-null float64
tutor_id                   69 non-null object
dtypes: float64(1), int64(8), object(13)
memory usage: 12.3+ KB

In [6]:
tutors[0:]

,user_id,gender,dob,main_language,description,institute_attended,occupation,occupation_degree,working_language,subject_1,...,subject_4_level,interest_1,time_interest_1,interest_2,time_interest_2,interest_3,time_interest_3,wished_salary,lesson_type,place
0,1c838e66-ed68-439d-9f9d-fd07c0d8907c,Female,1997-06-29,German,Ich studiere BWL-Industrie in Stuttgart und ka...,Duale Hochschule Baden-WÃ¼rttemberg in Stuttgar...,allgemeine Hochschulreife,HighSchool,German,German,...,10.0,Music,4,Art,4,Dance,4,30,Offline,GÃ¶ppingen
1,1e708c78-f6d5-4fbe-8909-c11cc3edf00a,Male,1970-11-23,German,"Ich bin Musiker, Musiktherapeut, Dirigent und ...","Erich-KÃ¤stner-Grundschule, Goethe-Gymnasium, F...",Musiker (Viola),Diplima,German,German,...,7.0,Music,5,MeetFriends,5,Other,5,40,Both,14195
2,6c12340c-1dee-486e-b9be-e6f94dbae12e,Male,1994-11-24,German,Ich bin Markus Johl und studiere Wirtschaftsin...,Ich war an der Kastanienbaumgrundschule und ha...,Leistungskurs Mathematik und Chemie,HighSchool,German,Math,...,NaN,VideoGames,4,ForeignLanguages,3,MeetFriends,4,40,Both,Berlin-Mitte
3,10df9bab-fb76-4e67-87b8-2349209e4751,Female,1994-12-01,German,"Hallo, ich bin Ann-Katrin, 23 Jahre alt und v...","Gymnasium Haan in Nordrhein-Westfalen, Emil-vo...","Englisch, Mathe, Erdkunde und Politik",HighSchool,German,Politics,...,9.0,MeetFriends,5,SocialCommitment,5,Tennis,3,20,Both,Passau
4,ca15069c-3664-42a6-9d98-9de7053fbd94,Male,1991-02-26,German,"Kenne mich mit Programmieren, Mathe und GrÃ¼nde...",TUM,Maschinenwesen,Bachelor,German,English,...,NaN,Reading,5,Tennis,3,StrengthTraining,3,60,Both,MÃ¼nchen
5,56bc0301-e5e4-4552-81cd-90ef9a3f26c8,Male,1997-05-11,German,"Mein Name ist Georg, ich studiere Wirtschaftsi...",Evangelische Grundschule Berlin Mitte Immanuel...,Allgemein,HighSchool,German,Math,...,12.0,Music,4,Reading,5,ForeignLanguages,3,40,Both,"Berlin Mitte, 10178"
6,8f124bc5-ee88-40b1-8f14-facd8f2fda0a,Male,1995-07-15,German,"Student Luft- und Raumfahrttechnik, 1.3 Studie...",Albert-Einstein-Gymnasium in BÃ¶blingen (BW) Un...,Luft- und Raumfahrttechnik Uni Stuttgart,Bachelor,German,Math,...,NaN,TableTennis,4,Mystery,3,Reading,3,30,Both,Berlin - Moabit
7,ffd55a08-f0bd-4deb-a801-fa4089327468,Male,1992-04-29,German,"Hey, ich bin Frederic, 25 Jahre, und Medizins...",Realschule Gymnasium UniversitÃ¤t TÃ¼bingen,1. Staatsexamen Medizin,Other,German,Chemistry,...,13.0,Foosball,4,MeetFriends,5,Other,5,40,Both,TÃ¼bingen
8,f63c7735-e572-4969-aed3-578c369a55c3,Male,1996-11-25,German,Ich bin der Spreaducation GrÃ¼nder und wÃ¼rde mi...,"Raichberg Gymnasium Ebersbach, Technische Univ...","Mathe, Physik, Chemie, Deutsch, Englisch, Fran...",HighSchool,German,Chemistry,...,13.0,Reading,3,Dance,5,SocialCommitment,2,50,Both,10965 Berlin
9,28d35678-ea41-47a3-8482-69bcf631dfcd,Female,1995-05-09,German,Ich habe eine sehr groÃŸe Leidenschaft fÃ¼r das ...,Schiller Gymnasium (Berlin) & Technische Unive...,"mit den Schwerpunkten: FranzÃ¶sisch, Kunst, Mat...",HighSchool,German,Math,...,10.0,ForeignLanguages,4,Music,4,Yoga,3,40,Both,Berlin Charlottenburg
10,bb8859f8-beaf-45f2-9127-af92c9642a2e,Male,1996-07-01,German,"Hey, ich bin Florian und studiere Englisch und...",Ich habe mein Abitur am Canisius Kolleg in Ber...,Englisch und Sozialwissenschafts LK,HighSchool,German,English,...,10.0,Rugby,4,MeetFriends,5,Theater,3,20,Offline,Berlin
11,c93c1f10-16a7-4010-be8f-de3f5669fe11,Female,1995-07-27,German,Hallo ich bin Tess und studiere Wirtschaftspsy...,Raichberg Gymnasium Hs Fresenius,Allgemeine Hochschulreife,HighSchool,German,Math,...,NaN,Music,4,Dance,4,MeetFriends,4,20,Both,KÃ¶ln
12,581e3d54-6a2e-4a1f-bdd5-6890fee295f1,Female,1993-05-27,German,"Ich bin 24 Jahre alt, studiere Mathematik und...",Ich studiere aktuell an der JGU Mainz und habe...,Leistungskurse Mathematik und Kunst,HighSchool,German,Math,...,NaN,Art,4,Fashion,3,Dance,3,50,Both,Niedernhausen
13,670bda40-8734-4055-9c93-526cba827752,Female,1994-04-22,German,"Ich bin Franziska, 23 Jahre alt, und studiere ...",Mein Abitur habe ich am Otto-Nagel-Gymnasium i...,allgemeine Hochschulreife,HighSchool,German,Math,...,NaN,Music,3,SocialCommitment,4,Climbing,2,20,Both,Dresden
14,95fb285c-dbd2-45cf-8238-9be1ec7e09b6,Male,1998-10-19,German,"Mein Name ist Florian, bin 19 Jahre alt und st...",- Melanchthon Gymnasium Berlin - HfTL (Duales ...,Zentral,HighSchool,German,Math,...,13.0,Reading,5,ForeignLanguages,4,Other,5,30,Both,Berlin
15,333f7165-8f35-4776-bb3e-78e711fd9f95,Male,1989-03-08,German,Ich bin Jonas! :),"FU Berlin, Peutinger Gymnasium",Mathematisch-naturwissenschaftlich,HighSchool,German,German,...,10.0,Reading,5,StrengthTraining,3,Music,2,20,Both,Berlin
16,6a1dfa14-0e5c-4644-b6cf-440b519808c0,Male,1996-11-13,German,Mein Name ist Jan und ich studiere American St...,UniversitÃ¤t Heidelberg,American Studies,Bachelor,German,German,...,NaN,VideoGames,5,Music,3,ForeignLanguages,5,20,Both,Edingen-Neckarhausen

In [7]:
tutors.iloc[2]

user_id                            6c12340c-1dee-486e-b9be-e6f94dbae12e
gender                                                             Male
dob                                                          1994-11-24
main_language                                                    German
description           Ich bin Markus Johl und studiere Wirtschaftsin...
institute_attended    Ich war an der Kastanienbaumgrundschule und ha...
occupation                          Leistungskurs Mathematik und Chemie
occupation_degree                                            HighSchool
working_language                                                 German
subject_1                                                          Math
subject_1_level                                                      13
subject_2                                                       Physics
subject_2_level                                                      10
subject_3                                                           NaN
subject_3_level                                                     NaN
subject_4                                                           NaN
subject_4_level                                                     NaN
interest_1                                                   VideoGames
time_interest_1                                                       4
interest_2                                             ForeignLanguages
time_interest_2                                                       3
interest_3                                                  MeetFriends
time_interest_3                                                       4
wished_salary                                                        40
lesson_type                                                        Both
place                                                      Berlin-Mitte
Name: 2, dtype: object

In [19]:
dic1 = tutees.iloc[[1,2,6,30], [0,3,16]]
dic1

                                 user_id  class_level subject_improve_2
1   6c28e282-6f8e-4184-96e4-81eaff0aa0b0            8            German
2   046059ed-ed1e-4982-ad7a-f1f55f6b1698            9           Spanish
6   4c557d50-791f-4214-9fe5-f6440c8c5f60            9              Math
30  b2f2a1bf-ac71-4575-bd40-8f21f979f648            9           Physics

# Transforming lists of feature-value mappings to vectors

### This transformer turns lists of mappings (dict-like objects) of feature names to feature values into Numpy arrays or scipy.sparse matrices for use with scikit-learn estimators.

### When feature values are strings, this transformer will do a binary one-hot (aka one-of-K) coding: one boolean-valued feature is constructed for each of the possible string values that the feature can take on

In [ ]:
import numpy as np
import scipy.sparse as sp
from pyspark import AccumulatorParam
from sklearn.externals import six
from sklearn.feature_extraction import DictVectorizer

from ..base import SparkBroadcasterMixin
from ..rdd import DictRDD
from ..utils.validation import check_rdd

In [13]:
from sklearn.feature_extraction import DictVectorizer
vec = DictVectorizer(sparse=True, dtype=int)
vec.fit_transform(dic1)

AttributeError: 'str' object has no attribute 'items'

In [ ]:
class SparkDictVectorizer(DictVectorizer, SparkBroadcasterMixin):

    """Transforms DictRDDs containing feature-value mappings to vectors.
    This transformer turns lists of mappings (dict-like objects) of feature
    names to feature values into Numpy arrays or scipy.sparse matrices for use
    with scikit-learn estimators.
    When feature values are strings, this transformer will do a binary one-hot
    (aka one-of-K) coding: one boolean-valued feature is constructed for each
    of the possible string values that the feature can take on. For instance,
    a feature "f" that can take on the values "ham" and "spam" will become two
    features in the output, one signifying "f=ham", the other "f=spam".
    Features that do not occur in a sample (mapping) will have a zero value
    in the resulting array/matrix.
    Parameters
    ----------
    dtype : callable, optional
        The type of feature values. Passed to Numpy array/scipy.sparse matrix
        constructors as the dtype argument.
    separator: string, optional
        Separator string used when constructing new features for one-hot
        coding.
    sparse: boolean, optional.
        Whether transform should produce scipy.sparse matrices.
        True by default.
    sort: boolean, optional.
        Whether feature_names_ and vocabulary_ should be sorted when fitting.
        True by default.
    Attributes
    ----------
    vocabulary_ : dict
        A dictionary mapping feature names to feature indices.
    feature_names_ : list
        A list of length n_features containing the feature names (e.g., "f=ham"
        and "f=spam").
    Examples
    --------
    >>> import numpy as np
    >>> from splearn.feature_extraction import SparkDictVectorizer
    >>> from splearn.rdd import ArrayRDD, DictRDD
    >>> D = np.array([{'foo': 1, 'bar': 2},
    >>>               {'foo': 3, 'baz': 1},
    >>>               {'bar': 2, 'baz': 4},
    >>>               {'foo':5}]).reshape((4,1))
    >>> D_rdd = sc.parallelize(D, 2)
    >>> D_dict = DictRDD(D_rdd, columns=('X',))
    >>> v = SparkDictVectorizer(sparse=False)
    >>> X = v.fit(D_dict)
    >>> v.transform(D_dict).collect()
    [(array([[ 2.,  0.,  1.],
             [ 0.,  1.,  3.]]),),
     (array([[ 2.,  4.,  0.],
             [ 0.,  0.,  5.]]),)]
    >>> test = sc.parallelize([{'foo': 4, 'unseen_feature': 3}])
    >>> print np.concatenate(v.transform(ArrayRDD(test)).collect())
    [[ 0.  0.  4.]]
    """

    __transient__ = ['feature_names_', 'vocabulary_']

    def fit(self, Z):
        """Learn a list of feature name -> indices mappings.
        Parameters
        ----------
        Z : DictRDD with column 'X'
            Dict(s) or Mapping(s) from feature names (arbitrary Python
            objects) to feature values (strings or convertible to dtype).
        Returns
        -------
        self
        """

In [ ]:
 X = Z[:, 'X'] if isinstance(Z, DictRDD) else Z

        """Create vocabulary
        """
        class SetAccum(AccumulatorParam):

            def zero(self, initialValue):
                return set(initialValue)

            def addInPlace(self, v1, v2):
                v1 |= v2
                return v1

        accum = X.context.accumulator(set(), SetAccum())

        def mapper(X, separator=self.separator):
            feature_names = []
            for x in X:
                for f, v in six.iteritems(x):
                    if isinstance(v, six.string_types):
                        f = "%s%s%s" % (f, self.separator, v)
                    feature_names.append(f)
            accum.add(set(feature_names))

        X.foreach(mapper)  # init vocabulary
        feature_names = list(accum.value)

        if self.sort:
            feature_names.sort()

        vocab = dict((f, i) for i, f in enumerate(feature_names))

        self.feature_names_ = feature_names
        self.vocabulary_ = vocab

        return self

In [ ]:
def transform(self, Z):
        """Transform ArrayRDD's (or DictRDD's 'X' column's) feature->value dicts
        to array or sparse matrix.
        Named features not encountered during fit or fit_transform will be
        silently ignored.
        
        Parameters
        ----------
        Z : ArrayRDD or DictRDD with column 'X' containing Mapping or
            iterable over Mappings, length = n_samples
            Dict(s) or Mapping(s) from feature names (arbitrary Python
            objects) to feature values (strings or convertible to dtype).
        Returns
        -------
        Z : transformed, containing {array, sparse matrix}
            Feature vectors; always 2-d.
        """
        mapper = self.broadcast(super(SparkDictVectorizer, self).transform,
                                Z.context)
        dtype = sp.spmatrix if self.sparse else np.ndarray
        return Z.transform(mapper, column='X', dtype=dtype)

    def fit_transform(self, Z):
        """Learn a list of feature name -> indices mappings and transform Z.
        Like fit(Z) followed by transform(Z).
        Parameters
        ----------
        Z : Z : ArrayRDD or DictRDD with column 'X' containing Mapping or
            iterable over Mappings
            Dict(s) or Mapping(s) from feature names (arbitrary Python
            objects) to feature values (strings or convertible to dtype).
        Returns
        -------
        Z : transformed, containing {array, sparse matrix}
            Feature vectors; always 2-d.
        """
return self.fit(Z).transform(Z)

In [ ]:
DataFrame.to_dict(orient='dict', into=<class 'dict'>)

In [ ]:
X_turned_category = pd.concat([pd.get_dummies(col,prefix=col_name) 
                    

for col_name, col in X_category.iteritems()],axis=1)

X_category: DataFrame each column represent a category type feature.

In [ ]:
#-*- coding:utf-8 -*-

"""
This module contains functions and classes for computing similarities across
a collection of vectors.
"""
#Authors: Marcel Caraciolo <marcel@muricoca.com>
#License: BSD Style


import numpy as np
from base import BaseSimilarity
from ..metrics.pairwise import loglikehood_coefficient


def find_common_elements(source_preferences, target_preferences):
    ''' Returns the preferences from both vectors '''
    src = dict(source_preferences)
    tgt = dict(target_preferences)

    inter = np.intersect1d(src.keys(), tgt.keys())

    common_preferences = zip(*[(src[item], tgt[item]) for item in inter \
            if not np.isnan(src[item]) and not np.isnan(tgt[item])])
    if common_preferences:
        return np.asarray([common_preferences[0]]), np.asarray([common_preferences[1]])
    else:
            return np.asarray([[]]), np.asarray([[]])

In [ ]:
###############################################################################
# User Similarity

class UserSimilarity(BaseSimilarity):
    '''
    Returns the degree of similarity, of two users, based on the their preferences.
    Implementations of this class define a notion of similarity between two users.
    Implementations should  return values in the range 0.0 to 1.0, with 1.0 representing
    perfect similarity.
    Parameters
    ----------
    `model`:  DataModel
         Defines the data model where data is fetched.
    `distance`: Function
         Pairwise Function between two vectors.
     `num_best`: int
         If it is left unspecified, similarity queries return a full list (one
         float for every item in the model, including the query item).
         If `num_best` is set, queries return `num_best` most similar items, as a
         sorted list.
    Methods
    ---------
    get_similarity()
    Return similarity of the `source_id` to a specific `target_id` in the model.
    get_similarities()
    Return similarity of the `source_id` to all sources in the model.
    Examples
    ---------
    >>> from scikits.crab.models.classes import MatrixPreferenceDataModel
    >>> from scikits.crab.metrics.pairwise import cosine_distances
    >>> from scikits.crab.similarities.basic_similarities import UserSimilarity
   
   '''

    def __init__(self, model, distance, num_best=None):
        BaseSimilarity.__init__(self, model, distance, num_best)

    def get_similarity(self, source_id, target_id):
        source_preferences = self.model.preferences_from_user(source_id)
        target_preferences = self.model.preferences_from_user(target_id)

        if self.model.has_preference_values():
            source_preferences, target_preferences = \
                find_common_elements(source_preferences, target_preferences)

        if source_preferences.ndim == 1 and target_preferences.ndim == 1:
            source_preferences = np.asarray([source_preferences])
            target_preferences = np.asarray([target_preferences])

        if self.distance == loglikehood_coefficient:
            return self.distance(self.model.items_count(), \
                source_preferences, target_preferences) \
                if not source_preferences.shape[1] == 0 and \
                not target_preferences.shape[1] == 0 else np.array([[np.nan]])

        #evaluate the similarity between the two users vectors.
        return self.distance(source_preferences, target_preferences) \
            if not source_preferences.shape[1] == 0 \
                and not target_preferences.shape[1] == 0 else np.array([[np.nan]])

    def get_similarities(self, source_id):
        return[(other_id, self.get_similarity(source_id, other_id))  for other_id, v in self.model]

    def __iter__(self):
        """
        For each object in model, compute the similarity function against all other objects and yield the result.
        """
        for source_id, preferences in self.model:
            yield source_id, self[source_id]

In [ ]:

###############################################################################
# Item Similarity


class ItemSimilarity(BaseSimilarity):
    '''
    Returns the degree of similarity, of two items, based on its preferences by the users.
    Implementations of this class define a notion of similarity between two items.
    Implementations should  return values in the range 0.0 to 1.0, with 1.0 representing
    perfect similarity.
    Parameters
    ----------
    `model`:  DataModel
         Defines the data model where data is fetched.
    `distance`: Function
         Pairwise Function between two vectors.
     `num_best`: int
         If it is left unspecified, similarity queries return a full list (one
         float for every item in the model, including the query item).
         If `num_best` is set, queries return `num_best` most similar items, as a
         sorted list.
    Methods
    ---------
    get_similarity()
    Return similarity of the `source_id` to a specific `target_id` in the model.
    get_similarities()
    Return similarity of the `source_id` to all sources in the model.
    Examples
    ---------
    >>> from scikits.crab.models.classes import MatrixPreferenceDataModel
    >>> from scikits.crab.metrics.pairwise import cosine_distances
    >>> from scikits.crab.similarities.basic_similarities import ItemSimilarity
    '''

    def __init__(self, model, distance, num_best=None):
        BaseSimilarity.__init__(self, model, distance, num_best)

    def get_similarity(self, source_id, target_id):
        source_preferences = self.model.preferences_for_item(source_id)
        target_preferences = self.model.preferences_for_item(target_id)

        if self.model.has_preference_values():
            source_preferences, target_preferences = \
                find_common_elements(source_preferences, target_preferences)

        if source_preferences.ndim == 1 and target_preferences.ndim == 1:
            source_preferences = np.asarray([source_preferences])
            target_preferences = np.asarray([target_preferences])

        if self.distance == loglikehood_coefficient:
            return self.distance(self.model.items_count(), \
                source_preferences, target_preferences) \
                if not source_preferences.shape[1] == 0 and \
                    not target_preferences.shape[1] == 0 else np.array([[np.nan]])

        #Evaluate the similarity between the two users vectors.
        return self.distance(source_preferences, target_preferences) \
            if not source_preferences.shape[1] == 0 and \
                not target_preferences.shape[1] == 0 else np.array([[np.nan]])

In [ ]:
def get_similarities(self, source_id):
        return [(other_id, self.get_similarity(source_id, other_id)) for other_id in self.model.item_ids()]

    def __iter__(self):
        """
        For each object in model, compute the similarity function against all other objects and yield the result.
        """
        for item_id in self.model.item_ids():
            yield item_id, self[item_id]

In [ ]:
import numpy as np
#from lightfm.datasets import fetch_movielens
from lightfm import LightFM

data = 

#print training and testing data
print(repr(data['train']))
print(repr(data['test']))

model = LightFM(loss='warp')
model.fit(data['train'], epochs=30, num_threads=2)

def sample_recommendation(model, data, user_ids):
    n_users, n_items = data['train'].shape
    for user_id in user_ids:
        known_positives = data['item_labels'][data['train'].tocsr()[user_id].indices]
        scores = model.predict(user_id, np.arange(n_items))
        top_items = data['item_labels'][np.argsort(-scores)]

        #print out the results
        print("User %s" % tutor_id)
        

        for x in known_positives[:3]:
            print("        %s" % x)

        print("   --Recommended Tutors:")

        for x in top_items[:3]:
            print("        %s" % x)

sample_recommendation(model, data, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])